version: 2

models:
  - name: stg_aircrafts
    description: table holds record for aircrafts
    columns:
      - name: aircraft_code_
        tests:
          - not_null 

      - name: range
        tests:
          - not_null 

      - name: model
        tests:
          - not_null 

      - name: _fivetran_synced
        tests:
          - not_null
          

  - name: stg_airports
    description: this table holds records for arports
    columns:
      - name: airport_name
        tests:
          - not_null
          
      - name: city
        tests:
          - not_null
          
      - name: timezone
        tests:
          - not_null
          
      - name: airport_code
        tests:
          - not_null
          
      - name: coordinates
      - name: _fivetran_synced


  - name: stg_seats
    description: this table records seats of aircrafts
    columns:
      - name: aircraft_code
        tests:
          - not_null
          - relationships:
              to: ref('airport_data_airport')
              field: airport_code
          
      - name: seat_no
        tests:
          - not_null
          
      - name: fare_conditions
        tests: 
          - not_null
    
      - name: _fivetran_synced

