version: 2

sources:
  - name: boarding_passes
    description: This table contains boarding_passes for passengers
    columns:
      - name: ticket_no
        tests:
          - not_null
      - name: flight_id
        tests:
          - not_null
      - name: boarding_no
        tests:
          - not_null
      - name: seat_no
        tests:
          - not_null

  - name: bookings
    description: This table stores bookings
    columns:
      - name: book_ref
        test:
          - not_null
      - name: book_date
        test:
          - not_null
      - name: total_amount
        test:
          - not_null

  - name: flights
    description: This table stores flight schedules
    columns:
      - name: flight_id
        test:
          - not_null
      - name: flight_no
        test:
          - not_null
      - name: scheduled_departure
      - name: scheduled_arrival           
      - name: departure_airport
      - name: arrival_airport
      - name: status
        tests:
           - not_null
      - name: aircraft_code
                - not_null
      - name: actual_departure
      - name: actual_arrival

  - name: tickets
    description: This table stores ticket 
    columns:
      - name: ticket_no
        test:
          - not_null
          - relationships:
              to: ref('ticket_flights')
              field: ticket_no
      - name: passenger_id
        tests:
          - not_null
      - name: passenger_name
        tests:
          - not_null
      - name: book_ref
        tests:
          - not_null

  - name: ticket_flight
    description: This table stores ticket 
    columns:
      - name: ticket_no
        test:
          - not_null       
      - name: flight_id
        test:
          - not_null         
      - name: fare_conditions
        test:
          - not_null         
      - name: amount
        test:
          - not_null
            
