version: 2

models:
  - name: stg_boarding_passes
    description: This table contains boarding_passes for passengers
    columns:
      - name: ticket_no
        tests:
          - not_null
      - name: flight_id
        tests:
          - not_null
      - name: boarding_no
        tests:
          - not_null
      - name: seat_no
        tests:
          - not_null

  - name: stg_bookings
    description: This table stores bookings
    columns:
      - name: book_ref
        tests:
          - unique:
              config:
                severity: warn
                error_if: ">100"
                warn_if: "< 10"
                limit: 10
                store_failures: true
                schema: testing
                          
      - name: book_date
        tests:
          - not_null

      - name: total_amount
        tests:
          - not_null


  - name: stg_flights
    description: This table stores flight schedules
    columns:
      - name: flight_id
        tests:
          - not_null
      - name: flight_no
        tests:
          - not_null
      - name: scheduled_departure
      - name: scheduled_arrival           
      - name: departure_airport
      - name: arrival_airport
      - name: status
        tests:
           - not_null
      - name: aircraft_code
                - not_null
      - name: actual_departure
      - name: actual_arrival

  - name: stg_tickets
    description: This table stores ticket 
    columns:
      - name: ticket_no
        tests:
          - not_null
          - relationships:
              to: ref('ticket_flights')
              field: ticket_no
      - name: passenger_id
        tests:
          - not_null
      - name: passenger_name
        tests:
          - not_null
      - name: book_ref
        tests:
          - not_null

  - name: stg_ticket_flights
    description: This table stores ticket 
    columns:
      - name: ticket_no
        tests:
          - not_null       
      - name: flight_id
        tests:
          - not_null         
      - name: fare_conditions
        tests:
          - not_null         
      - name: amount
        tests:
          - not_null



        # Invalid sources config given in models/staging/snowpipe/schema.yml 
        # @ sources: {'name': 'stg_boarding_passes', 'description': 
        #   'This table contains boarding_passes for passengers', 
        # 'columns': [{'name': 'ticket_no', 'tests': ['not_null']},
        #  {'name': 'flight_id', 'tests': ['not_null']},
        #   {'name': 'boarding_no', 'tests': ['not_null']}, 
        #   {'name': 'seat_no', 'tests': ['not_null']}]} 

        #   - at path []: Additional properties are not allowed 
        #   ('columns' was unexpected)     

